Wed Sep 14 14:43:06 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:42:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:42:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<MissingSourceFile: no such file to load -- eventmachine>
Thu Sep 15 15:47:31 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Fri Sep 16 10:29:19 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Mon Sep 19 13:49:56 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Mon Sep 19 14:04:53 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<MissingSourceFile: no such file to load -- eventmachine>
Tue Sep 20 09:44:35 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Wed Sep 21 14:58:31 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Mon Sep 26 10:11:31 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:42:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:42:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<LoadError: no such file to load -- daemons>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<Mysql::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
#<Errno::EAGAIN: Resource temporarily unavailable>
#<MissingSourceFile: no such file to load -- eventmachine>
Mon Sep 26 10:14:21 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Mon Sep 26 10:34:43 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:57:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `loop'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:44:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Mon Sep 26 10:58:34 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:42:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:42:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
Mon Sep 26 10:58:55 -0400 2011
SIGTERM
["/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:42:in `sleep'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:42:in `watch'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:84:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `fork'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:64:in `start_with_pidfile'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/monitor.rb:111:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application_group.rb:149:in `create_monitor'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/application.rb:282:in `start'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/controller.rb:70:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:145:in `run'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `call'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons/cmdline.rb:109:in `catch_exceptions'", "/Users/cmmagid/Developer/.rvm/gems/ruby-1.8.7-p302@rails2newwebiva/gems/daemons-1.1.3/lib/daemons.rb:144:in `run'", "/Users/cmmagid/rails_projects/Webiva/script/workling_client:17"]
*** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
#<MissingSourceFile: no such file to load -- eventmachine>
*** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<fatal: exception reentered>
#<Errno::ESRCH: No such process>
#<LoadError: no such file to load -- daemons>
#<Workling::QueueserverNotFoundError: config/workling.yml configured to connect to queue server on localhost:22122 for this environment. could not connect to queue server on this host:port. for starling users: pass starling the port with -p flag when starting it. If you don't want to use Starling, then explicitly set Workling::Remote.dispatcher (see README for an example)>
#<Workling::QueueserverNotFoundError: config/workling.yml configured to connect to queue server on localhost:22122 for this environment. could not connect to queue server on this host:port. for starling users: pass starling the port with -p flag when starting it. If you don't want to use Starling, then explicitly set Workling::Remote.dispatcher (see README for an example)>
#<MemCache::MemCacheError: No active servers>
#<Errno::ECONNREFUSED: Connection refused - connect(2)>
#<Workling::QueueserverNotFoundError: config/workling.yml configured to connect to queue server on localhost:22122 for this environment. could not connect to queue server on this host:port. for starling users: pass starling the port with -p flag when starting it. If you don't want to use Starling, then explicitly set Workling::Remote.dispatcher (see README for an example)>
#<MemCache::MemCacheError: No active servers>
#<Errno::ECONNREFUSED: Connection refused - connect(2)>
#<Workling::QueueserverNotFoundError: config/workling.yml configured to connect to queue server on localhost:22122 for this environment. could not connect to queue server on this host:port. for starling users: pass starling the port with -p flag when starting it. If you don't want to use Starling, then explicitly set Workling::Remote.dispatcher (see README for an example)>
#<MemCache::MemCacheError: No active servers>
#<Errno::ECONNREFUSED: Connection refused - connect(2)>
#<Workling::QueueserverNotFoundError: config/workling.yml configured to connect to queue server on localhost:22122 for this environment. could not connect to queue server on this host:port. for starling users: pass starling the port with -p flag when starting it. If you don't want to use Starling, then explicitly set Workling::Remote.dispatcher (see README for an example)>
#<MemCache::MemCacheError: No active servers>
#<Errno::ECONNREFUSED: Connection refused - connect(2)>
#<Workling::QueueserverNotFoundError: config/workling.yml configured to connect to queue server on localhost:22122 for this environment. could not connect to queue server on this host:port. for starling users: pass starling the port with -p flag when starting it. If you don't want to use Starling, then explicitly set Workling::Remote.dispatcher (see README for an example)>
#<MemCache::MemCacheError: No active servers>
#<Errno::ECONNREFUSED: Connection refused - connect(2)>
#<Workling::QueueserverNotFoundError: config/workling.yml configured to connect to queue server on localhost:22122 for this environment. could not connect to queue server on this host:port. for starling users: pass starling the port with -p flag when starting it. If you don't want to use Starling, then explicitly set Workling::Remote.dispatcher (see README for an example)>
#<MemCache::MemCacheError: No active servers>
#<Errno::ECONNREFUSED: Connection refused - connect(2)>
#<Workling::QueueserverNotFoundError: config/workling.yml configured to connect to queue server on localhost:22122 for this environment. could not connect to queue server on this host:port. for starling users: pass starling the port with -p flag when starting it. If you don't want to use Starling, then explicitly set Workling::Remote.dispatcher (see README for an example)>
#<MemCache::MemCacheError: No active servers>
#<Errno::ECONNREFUSED: Connection refused - connect(2)>
#<Workling::QueueserverNotFoundError: config/workling.yml configured to connect to queue server on localhost:22122 for this environment. could not connect to queue server on this host:port. for starling users: pass starling the port with -p flag when starting it. If you don't want to use Starling, then explicitly set Workling::Remote.dispatcher (see README for an example)>
#<MemCache::MemCacheError: No active servers>
#<Errno::ECONNREFUSED: Connection refused - connect(2)>
#<Workling::QueueserverNotFoundError: config/workling.yml configured to connect to queue server on localhost:22122 for this environment. could not connect to queue server on this host:port. for starling users: pass starling the port with -p flag when starting it. If you don't want to use Starling, then explicitly set Workling::Remote.dispatcher (see README for an example)>
#<MemCache::MemCacheError: No active servers>
#<Errno::ECONNREFUSED: Connection refused - connect(2)>
#<NameError: uninitialized constant Workling::Return::Store::Base>
#<MissingSourceFile: no such file to load -- eventmachine>
